/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package associations;

public class Main {

  public static void main(String[] args){
  // Instantiate objects to test your code
  }
  
}
